[project]
name = "infer-return-type"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.5",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
]
